import 'package:flutter/material.dart';

const domainURL = 'http://girl-period.uplosse.com/api/';
String login = domainURL + "login";
String regsiter = domainURL + "register";
String GetArticles = domainURL + "get-articles";
String getpolicies = domainURL + "privacy-policy";
String addnotes = domainURL + "add-user-notes";
String getSetting = domainURL + "setting";
String updateprofileonserver = domainURL + "user-profile";
String upadatesettingsinserver = domainURL + "setting/update";
String senperiodtoserver = domainURL + "add-period-date";
String nexperiod = domainURL + "get-next-period-date";
String updatesetings = domainURL + "setting/update";
String checklogin = domainURL + "check-login";
String getnotes = domainURL + "get-user-notes";
String getnotescountapi = domainURL + "get-user-notes-count";
String firstlogin = domainURL + "login-for-first";
String logindemo = domainURL + "login-demo-model";
String notecountbymonth = domainURL + "get-all-notes-by-months";
String getperiodsdate = domainURL + "get-period-date";
String getendperioddate = domainURL + "period-ended-yet";
String backupapi = domainURL + "take-back-up";
