name: vietnamese
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  velocity_x: 
  font_awesome_flutter: 
  flutter_cupertino_date_picker: ^1.0.26+2
  http:
  flutter_rating_bar:
  flutter_pin_code_fields: ^1.1.0
  vertical_weight_slider :  
  lunar_calendar: ^1.0.1
  table_calendar: 
  device_info: ^2.0.2
  rate_my_app: ^1.0.0+2 
  swipedetector: 1.2.0
  fluttertoast:
  shared_preferences:
  flutter_share: ^2.0.0 
  flutter_facebook_login: 
  google_sign_in:
  flutter_html: ^0.8.2
  email_validator: ^1.0.4
  flutter_launcher_icons: "^0.8.0"
  page_transition: 
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/login/
    - assets/images/dashboard/
    - assets/icons/
    - assets/fontsIcon/

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Black.ttf
          weight: 900
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
    - family: iconapp
      fonts:
        - asset: assets/fontsIcon/MyFlutterApp.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/home_white.png"

